### ISSUE TITLE
Resample is only at a constant frequency

### ISSUE THREAD

**Issue by HoagyC** [ai-safety-foundation/sparse_autoencoder#102]
At the moment we just pass in a fixed `resample_frequency` to `run_pipeline`.

The Anthropic paper resamples after 200M activations - but only for the first 1B tokens, after which they no longer resamplel

Options:
* More flexible frequency - could pass in a list of intervals?
* Just use multiple calls to `run_pipeline`.

**Comment by HoagyC** [comment]
also, if we're going down the route of multiple calls to `run_pipeline`, `resample_frequency` should have a None/falsy option. 
Happy to implement either, do you have a preference @alan-cooney?

**Comment by HoagyC** [comment]
my preference would probably be to keep it simple internally and just do multiple calls but i feel like the library is designed around max flexibility so perhaps it should be configurable?

**Comment by alan-cooney** [comment]
I'm wondering if we need to delegate all of this to the resample class, so it's removed from the already bloated pipeline?

Maybe we call the resampler with the neuron activity for every batch, and most of the time it can just update aggregate metrics but sometimes it will do a full resample? The only thing we'd want to keep in the pipeline is then calling it and updating the model and optimizer state if it responds with anything (as we don't want to couple the class state updates).

What do you think?

**Comment by HoagyC** [comment]
(deleted previous version of my comment as i hadn't read yours properly) 
Yeah I think that makes sense, I was thinking of just passing a function to the resampler class on init which takes an int (i suppose total_steps but could be steps_since_resampled) and returns a binary on whether or not to resample.

Could definitely go your route - concretely I guess you'd retain the update section of resample_neurons as a parameter_update function, and the resampler class gets a more general function that decides whether to run the main `resample_dead_neurons` and returns either None or a structured tuple of parameter updates. That sound right?

**Comment by HoagyC** [comment]
Tried to fix this with PR #105
