### ISSUE TITLE
Should be a way to upload models automatically

### ISSUE THREAD

**Issue by HoagyC** [ai-safety-foundation/sparse_autoencoder#140]
System should work with aws S3 or similar. should check that it can upload a dummy file at the beginning and then upload the checkpoints as they are made.

Should probably be a separate, optional set of hparams to pass to pipeline for the basics like bucket_name and access_key, and then get the private keys from a secrets.json

needs to be careful with uploading checkpoints from `../../.checkpoints` as the multiple `..` cause errors with my existing aws code.

I can add this, just want to see if there are any suggestions or disagreements on how to add this. Will have a look at doing it this eve.

**Comment by alan-cooney** [comment]
Sounds good! Maybe shove this into the abstract model class? And then we can call from the pipeline?

For referencing directories use pathlib.Path

**Comment by alan-cooney** [comment]
Up to you - no strong views on this
