### ISSUE TITLE
Create clear specs for how much GPU Memory is needed to run demos/benchmarks. 

### ISSUE THREAD

**Issue by jbloomAus** [ai-safety-foundation/sparse_autoencoder#22]
Tried to run the notebooks and ran out of Memory when 
- NVIDIA A10G (24GiB)
- 1 GPUs x 8 CPUs | 32GiB
 
I'd understand if we needed something beefier in the real world but for demos it might be good to handle something smaller?

**Comment by alan-cooney** [comment]
Looks like this is fixed now with a smaller demo and more efficient code?

**Comment by jbloomAus** [comment]
yeah, agreed. It's using tiny stories now :)
