### ISSUE TITLE
Make demo work 

### ISSUE THREAD

**Issue by ArthurConmy** [ai-safety-foundation/sparse_autoencoder#47]
@alan-cooney what's up with the demo deleting the pipeline? Is there currently a workaround for the next two hours? Can I revert the deletions or will that cause problems?

**Comment by ArthurConmy** [comment]
FYI the demo currently uses a SoLU model (not GeLU), Pile data and GPT-2 tokenizer; seems inconsistent

**Comment by alan-cooney** [comment]
Been refactoring but it should be working at https://github.com/ai-safety-foundation/sparse_autoencoder/pull/50 (will merge shortly)
