### ISSUE TITLE
Hot take 2: easier install

### ISSUE THREAD

**Issue by ArthurConmy** [ai-safety-foundation/sparse_autoencoder#54]
I think that we will get less collaborators with the current install setup. I know how to install poetry etc but without quick easy `pip install -e .` (and `pip install -U torch==1.13.1` when my GPU isn't compatible!) there's an "ugh field" for me before I contribute.

Open to disagreeement here, just like the other issue!

**Comment by alan-cooney** [comment]
The problem with using pip is that pip doesn't check for conflicts properly, so you end up getting a load of issues with dependency conflicts down the line that are very hard to debug. But if it's a huge issue we could probably work something out.

I would say that whilst `poetry` isn't as commonly used as pip, it is more commonly used by big libraries for their dev setup

**Comment by alan-cooney** [comment]
Closing for now as I'm happy it's the least worst option

**Comment by ArthurConmy** [comment]
I was hoping for a solution where we use `poetry`, but the `pyproject.toml` is used by `pip` by default and works fine - this doesn't work with our setup as pip does not install everything needed. Is this also infeasible?

**Comment by alan-cooney** [comment]
For people using the tool but not working on the codebase, they can just `pip install sparse_autoencoder`.

**Comment by alan-cooney** [comment]
(as in it's on pypi)

**Comment by jbloomAus** [comment]
Yeah, this confuses me. You can install with pip, it's just that for devs, you're always going to want a higher standard and poetry is the least bad option here.

**Comment by ArthurConmy** [comment]
I don't think pypi will help much for the next ~month as I expect anyone using the library will want to modify internals in order to train SAEs with their modifications

**Comment by alan-cooney** [comment]
Yeah I think that's fair for the next month, but keen to just keep as is to avoid issues down the road with converting back to poetry. Hopefully it's fine for most people as it only takes a few minutes to get setup with poetry
