### ISSUE TITLE
Log L0 norm to weights and biases. 

### ISSUE THREAD

**Issue by jbloomAus** [ai-safety-foundation/sparse_autoencoder#87]
See [here](https://transformer-circuits.pub/2023/monosemantic-features#:~:text=The%20average%20number,transformer%E2%80%99s%20activation%20dimensionality.)

To do:
- [ ] Add L0 Metric
- [ ] Make sure it gets logged to wandb.

**Comment by alan-cooney** [comment]
FYI the loss modules log this out of the box now - so I think it's just if we also want L0 on reconstruction that we should add as a metrics class

**Comment by alan-cooney** [comment]
Done
